steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-download-auctions/build:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', './build-env.Dockerfile',
      '-t', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-download-auctions/build',
      '--cache-from', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-download-auctions/build:latest',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'tag',
      'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-download-auctions/build',
      'steamwheedle-cartel/run-download-auctions/build'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-download-auctions/runtime:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', './runtime-env.Dockerfile',
      '-t', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-download-auctions/runtime',
      '--cache-from', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-download-auctions/runtime:latest',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-download-auctions/runtime'
    ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'beta', 'run', 'deploy',
      'run-download-auctions',
      '--image', 'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-download-auctions/runtime',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--no-allow-unauthenticated',
      '--timeout', '120s',
      '--concurrency', '80',
      '--memory', '512MB'
    ]
images: [
  'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-download-auctions/build:latest',
  'gcr.io/$PROJECT_ID/steamwheedle-cartel/run-download-auctions/runtime:latest'
]
